/*

MIT License

Copyright (c) 2017 Sean Ross-Ross

See License in the root of this repo.

*/

// This file was automatically generated by lister-gen

package v1alpha1

// TestRunListerExpansion allows custom methods to be added to
// TestRunLister.
type TestRunListerExpansion interface{}

// TestRunNamespaceListerExpansion allows custom methods to be added to
// TestRunNamespaceLister.
type TestRunNamespaceListerExpansion interface{}

// TestTemplateListerExpansion allows custom methods to be added to
// TestTemplateLister.
type TestTemplateListerExpansion interface{}

// TestTemplateNamespaceListerExpansion allows custom methods to be added to
// TestTemplateNamespaceLister.
type TestTemplateNamespaceListerExpansion interface{}
