// +build !ignore_autogenerated

/*

MIT License

Copyright (c) 2017 Sean Ross-Ross

See License in the root of this repo.

*/

// This file was autogenerated by conversion-gen. Do not edit it manually!

package v1alpha1

import (
	tester "github.com/srossross/k8s-test-controller/pkg/apis/tester"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	unsafe "unsafe"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1alpha1_TestRun_To_tester_TestRun,
		Convert_tester_TestRun_To_v1alpha1_TestRun,
		Convert_v1alpha1_TestRunList_To_tester_TestRunList,
		Convert_tester_TestRunList_To_v1alpha1_TestRunList,
		Convert_v1alpha1_TestRunSpec_To_tester_TestRunSpec,
		Convert_tester_TestRunSpec_To_v1alpha1_TestRunSpec,
		Convert_v1alpha1_TestRunStatus_To_tester_TestRunStatus,
		Convert_tester_TestRunStatus_To_v1alpha1_TestRunStatus,
		Convert_v1alpha1_TestTemplate_To_tester_TestTemplate,
		Convert_tester_TestTemplate_To_v1alpha1_TestTemplate,
		Convert_v1alpha1_TestTemplateList_To_tester_TestTemplateList,
		Convert_tester_TestTemplateList_To_v1alpha1_TestTemplateList,
		Convert_v1alpha1_TestTemplateSpec_To_tester_TestTemplateSpec,
		Convert_tester_TestTemplateSpec_To_v1alpha1_TestTemplateSpec,
	)
}

func autoConvert_v1alpha1_TestRun_To_tester_TestRun(in *TestRun, out *tester.TestRun, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_TestRunSpec_To_tester_TestRunSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_TestRunStatus_To_tester_TestRunStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_TestRun_To_tester_TestRun is an autogenerated conversion function.
func Convert_v1alpha1_TestRun_To_tester_TestRun(in *TestRun, out *tester.TestRun, s conversion.Scope) error {
	return autoConvert_v1alpha1_TestRun_To_tester_TestRun(in, out, s)
}

func autoConvert_tester_TestRun_To_v1alpha1_TestRun(in *tester.TestRun, out *TestRun, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_tester_TestRunSpec_To_v1alpha1_TestRunSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_tester_TestRunStatus_To_v1alpha1_TestRunStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_tester_TestRun_To_v1alpha1_TestRun is an autogenerated conversion function.
func Convert_tester_TestRun_To_v1alpha1_TestRun(in *tester.TestRun, out *TestRun, s conversion.Scope) error {
	return autoConvert_tester_TestRun_To_v1alpha1_TestRun(in, out, s)
}

func autoConvert_v1alpha1_TestRunList_To_tester_TestRunList(in *TestRunList, out *tester.TestRunList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]tester.TestRun)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_TestRunList_To_tester_TestRunList is an autogenerated conversion function.
func Convert_v1alpha1_TestRunList_To_tester_TestRunList(in *TestRunList, out *tester.TestRunList, s conversion.Scope) error {
	return autoConvert_v1alpha1_TestRunList_To_tester_TestRunList(in, out, s)
}

func autoConvert_tester_TestRunList_To_v1alpha1_TestRunList(in *tester.TestRunList, out *TestRunList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items == nil {
		out.Items = make([]TestRun, 0)
	} else {
		out.Items = *(*[]TestRun)(unsafe.Pointer(&in.Items))
	}
	return nil
}

// Convert_tester_TestRunList_To_v1alpha1_TestRunList is an autogenerated conversion function.
func Convert_tester_TestRunList_To_v1alpha1_TestRunList(in *tester.TestRunList, out *TestRunList, s conversion.Scope) error {
	return autoConvert_tester_TestRunList_To_v1alpha1_TestRunList(in, out, s)
}

func autoConvert_v1alpha1_TestRunSpec_To_tester_TestRunSpec(in *TestRunSpec, out *tester.TestRunSpec, s conversion.Scope) error {
	out.Selector = (*v1.LabelSelector)(unsafe.Pointer(in.Selector))
	out.MaxJobs = in.MaxJobs
	out.MaxFail = in.MaxFail
	return nil
}

// Convert_v1alpha1_TestRunSpec_To_tester_TestRunSpec is an autogenerated conversion function.
func Convert_v1alpha1_TestRunSpec_To_tester_TestRunSpec(in *TestRunSpec, out *tester.TestRunSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_TestRunSpec_To_tester_TestRunSpec(in, out, s)
}

func autoConvert_tester_TestRunSpec_To_v1alpha1_TestRunSpec(in *tester.TestRunSpec, out *TestRunSpec, s conversion.Scope) error {
	out.Selector = (*v1.LabelSelector)(unsafe.Pointer(in.Selector))
	out.MaxJobs = in.MaxJobs
	out.MaxFail = in.MaxFail
	return nil
}

// Convert_tester_TestRunSpec_To_v1alpha1_TestRunSpec is an autogenerated conversion function.
func Convert_tester_TestRunSpec_To_v1alpha1_TestRunSpec(in *tester.TestRunSpec, out *TestRunSpec, s conversion.Scope) error {
	return autoConvert_tester_TestRunSpec_To_v1alpha1_TestRunSpec(in, out, s)
}

func autoConvert_v1alpha1_TestRunStatus_To_tester_TestRunStatus(in *TestRunStatus, out *tester.TestRunStatus, s conversion.Scope) error {
	out.Status = in.Status
	out.Message = in.Message
	out.Success = in.Success
	return nil
}

// Convert_v1alpha1_TestRunStatus_To_tester_TestRunStatus is an autogenerated conversion function.
func Convert_v1alpha1_TestRunStatus_To_tester_TestRunStatus(in *TestRunStatus, out *tester.TestRunStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_TestRunStatus_To_tester_TestRunStatus(in, out, s)
}

func autoConvert_tester_TestRunStatus_To_v1alpha1_TestRunStatus(in *tester.TestRunStatus, out *TestRunStatus, s conversion.Scope) error {
	out.Status = in.Status
	out.Message = in.Message
	out.Success = in.Success
	return nil
}

// Convert_tester_TestRunStatus_To_v1alpha1_TestRunStatus is an autogenerated conversion function.
func Convert_tester_TestRunStatus_To_v1alpha1_TestRunStatus(in *tester.TestRunStatus, out *TestRunStatus, s conversion.Scope) error {
	return autoConvert_tester_TestRunStatus_To_v1alpha1_TestRunStatus(in, out, s)
}

func autoConvert_v1alpha1_TestTemplate_To_tester_TestTemplate(in *TestTemplate, out *tester.TestTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_TestTemplateSpec_To_tester_TestTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_TestTemplate_To_tester_TestTemplate is an autogenerated conversion function.
func Convert_v1alpha1_TestTemplate_To_tester_TestTemplate(in *TestTemplate, out *tester.TestTemplate, s conversion.Scope) error {
	return autoConvert_v1alpha1_TestTemplate_To_tester_TestTemplate(in, out, s)
}

func autoConvert_tester_TestTemplate_To_v1alpha1_TestTemplate(in *tester.TestTemplate, out *TestTemplate, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_tester_TestTemplateSpec_To_v1alpha1_TestTemplateSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_tester_TestTemplate_To_v1alpha1_TestTemplate is an autogenerated conversion function.
func Convert_tester_TestTemplate_To_v1alpha1_TestTemplate(in *tester.TestTemplate, out *TestTemplate, s conversion.Scope) error {
	return autoConvert_tester_TestTemplate_To_v1alpha1_TestTemplate(in, out, s)
}

func autoConvert_v1alpha1_TestTemplateList_To_tester_TestTemplateList(in *TestTemplateList, out *tester.TestTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]tester.TestTemplate)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_TestTemplateList_To_tester_TestTemplateList is an autogenerated conversion function.
func Convert_v1alpha1_TestTemplateList_To_tester_TestTemplateList(in *TestTemplateList, out *tester.TestTemplateList, s conversion.Scope) error {
	return autoConvert_v1alpha1_TestTemplateList_To_tester_TestTemplateList(in, out, s)
}

func autoConvert_tester_TestTemplateList_To_v1alpha1_TestTemplateList(in *tester.TestTemplateList, out *TestTemplateList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	if in.Items == nil {
		out.Items = make([]TestTemplate, 0)
	} else {
		out.Items = *(*[]TestTemplate)(unsafe.Pointer(&in.Items))
	}
	return nil
}

// Convert_tester_TestTemplateList_To_v1alpha1_TestTemplateList is an autogenerated conversion function.
func Convert_tester_TestTemplateList_To_v1alpha1_TestTemplateList(in *tester.TestTemplateList, out *TestTemplateList, s conversion.Scope) error {
	return autoConvert_tester_TestTemplateList_To_v1alpha1_TestTemplateList(in, out, s)
}

func autoConvert_v1alpha1_TestTemplateSpec_To_tester_TestTemplateSpec(in *TestTemplateSpec, out *tester.TestTemplateSpec, s conversion.Scope) error {
	out.Template = in.Template
	return nil
}

// Convert_v1alpha1_TestTemplateSpec_To_tester_TestTemplateSpec is an autogenerated conversion function.
func Convert_v1alpha1_TestTemplateSpec_To_tester_TestTemplateSpec(in *TestTemplateSpec, out *tester.TestTemplateSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_TestTemplateSpec_To_tester_TestTemplateSpec(in, out, s)
}

func autoConvert_tester_TestTemplateSpec_To_v1alpha1_TestTemplateSpec(in *tester.TestTemplateSpec, out *TestTemplateSpec, s conversion.Scope) error {
	out.Template = in.Template
	return nil
}

// Convert_tester_TestTemplateSpec_To_v1alpha1_TestTemplateSpec is an autogenerated conversion function.
func Convert_tester_TestTemplateSpec_To_v1alpha1_TestTemplateSpec(in *tester.TestTemplateSpec, out *TestTemplateSpec, s conversion.Scope) error {
	return autoConvert_tester_TestTemplateSpec_To_v1alpha1_TestTemplateSpec(in, out, s)
}
