/*

MIT License

Copyright (c) 2017 Sean Ross-Ross

See License in the root of this repo.

*/

// This file was automatically generated by informer-gen

package v1alpha1

import (
	internalinterfaces "github.com/srossross/k8s-test-controller/pkg/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// TestRuns returns a TestRunInformer.
	TestRuns() TestRunInformer
	// TestTemplates returns a TestTemplateInformer.
	TestTemplates() TestTemplateInformer
}

type version struct {
	internalinterfaces.SharedInformerFactory
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory) Interface {
	return &version{f}
}

// TestRuns returns a TestRunInformer.
func (v *version) TestRuns() TestRunInformer {
	return &testRunInformer{factory: v.SharedInformerFactory}
}

// TestTemplates returns a TestTemplateInformer.
func (v *version) TestTemplates() TestTemplateInformer {
	return &testTemplateInformer{factory: v.SharedInformerFactory}
}
